INSERT INTO imagem (
    nome_original,
    object_key,
    bucket,
    content_type,
    tamanho,
    principal,
    veiculo_id
)
VALUES
    (
        'corolla-frente.jpg',
        'veiculos/1/corolla-frente.jpg',
        'loja-veiculos',
        'image/jpeg',
        245678,
        TRUE,
        1
    ),
    (
        'corolla-lateral.jpg',
        'veiculos/1/corolla-lateral.jpg',
        'loja-veiculos',
        'image/jpeg',
        198432,
        FALSE,
        1
    ),
    (
        'corolla-interior.jpg',
        'veiculos/1/corolla-interior.jpg',
        'loja-veiculos',
        'image/jpeg',
        312455,
        FALSE,
        1
    ),
    (
        'civic-frente.jpg',
        'veiculos/2/civic-frente.jpg',
        'loja-veiculos',
        'image/jpeg',
        287654,
        TRUE,
        2
    ),
    (
        'civic-painel.jpg',
        'veiculos/2/civic-painel.jpg',
        'loja-veiculos',
        'image/jpeg',
        223344,
        FALSE,
        2
    );