INSERT INTO modelo (nome, marca_id, ativo)
VALUES ('Argo', 1, b'1'),
       ('Cronos', 1, b'1'),
       ('Mobi', 1, b'1'),
       ('Toro', 1, b'1'),
       ('Pulse', 1, b'1'),
       ('Gol', 2, b'1'),
       ('Polo', 2, b'1'),
       ('Virtus', 2, b'1'),
       ('T-Cross', 2, b'1'),
       ('Nivus', 2, b'1'),
       ('Onix', 3, b'1'),
       ('Onix Plus', 3, b'1'),
       ('Tracker', 3, b'1'),
       ('S10', 3, b'1'),
       ('Spin', 3, b'1'),
       ('Corolla', 4, b'1'),
       ('Corolla Cross', 4, b'1'),
       ('Hilux', 4, b'1'),
       ('Yaris', 4, b'1'),
       ('SW4', 4, b'1'),
       ('HB20', 5, b'1'),
       ('HB20S', 5, b'1'),
       ('Creta', 5, b'1'),
       ('Tucson', 5, b'1'),
       ('Santa Fe', 5, b'1'),
       ('Renegade', 6, b'1'),
       ('Compass', 6, b'1'),
       ('Commander', 6, b'1'),
       ('Cherokee', 6, b'1'),
       ('Wrangler', 6, b'1'),
       ('Kwid', 7, b'1'),
       ('Logan', 7, b'1'),
       ('Sandero', 7, b'1'),
       ('Duster', 7, b'1'),
       ('Captur', 7, b'1'),
       ('Civic', 8, b'1'),
       ('City', 8, b'0'),
       ('HR-V', 8, b'0'),
       ('Fit', 8, b'0'),
       ('WR-V', 8, b'0'),
       ('Kicks', 9, b'0'),
       ('Versa', 9, b'0'),
       ('Frontier', 9, b'0'),
       ('Sentra', 9, b'0'),
       ('March', 9, b'0'),
       ('Ka', 10, b'0'),
       ('EcoSport', 10, b'0'),
       ('Ranger', 10, b'0'),
       ('Fusion', 10, b'0'),
       ('Focus', 10, b'0');