INSERT INTO opcional (nome) VALUES
                                ('Ar condicionado'),
                                ('Direção hidráulica'),
                                ('Direção elétrica'),
                                ('Vidros elétricos'),
                                ('Travas elétricas'),
                                ('Alarme'),
                                ('Airbag motorista'),
                                ('Airbag passageiro'),
                                ('Airbags laterais'),
                                ('Freios ABS'),
                                ('Controle de estabilidade'),
                                ('Controle de tração'),
                                ('Central multimídia'),
                                ('Bluetooth'),
                                ('Entrada USB'),
                                ('Câmera de ré'),
                                ('Sensor de estacionamento traseiro'),
                                ('Sensor de estacionamento dianteiro'),
                                ('Piloto automático'),
                                ('Piloto automático adaptativo'),
                                ('Computador de bordo'),
                                ('Bancos de couro'),
                                ('Banco do motorista com ajuste elétrico'),
                                ('Banco do motorista com ajuste de altura'),
                                ('Volante multifuncional'),
                                ('Volante com regulagem de altura'),
                                ('Volante com regulagem de profundidade'),
                                ('Chave presencial'),
                                ('Partida sem chave'),
                                ('Teto solar'),
                                ('Teto panorâmico'),
                                ('Faróis de LED'),
                                ('Faróis de neblina'),
                                ('Luzes diurnas de LED'),
                                ('Rodas de liga leve'),
                                ('Rodas esportivas'),
                                ('Retrovisores elétricos'),
                                ('Retrovisores com rebatimento elétrico'),
                                ('Desembaçador traseiro'),
                                ('Limpador traseiro'),
                                ('Isofix'),
                                ('Assistente de partida em rampa'),
                                ('Frenagem automática de emergência'),
                                ('Reconhecimento de faixa'),
                                ('Monitoramento de ponto cego'),
                                ('Carregador sem fio'),
                                ('Apple CarPlay'),
                                ('Android Auto'),
                                ('GPS integrado');