spring.profiles.active=dev

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.servlet.context-path=/api

logging.level.org.springframework.security=DEBUG

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always