spring.datasource.url=jdbc:mysql://localhost:3306/loja_de_carros
spring.datasource.username=root
spring.datasource.password=root
storage.provider=local
storage.local.root=uploads
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.flyway.enabled=true
logging.level.org.hibernate.tool.schema=DEBUG
spring.jpa.hibernate.ddl-auto=validate
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/loja-de-carros
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8081/realms/loja-de-carros/protocol/openid-connect/certs
spring.security.oauth2.resourceserver.jwt.audiences[0]=loja-de-carros-api