name: Continuous Integration

on:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: maven

      - name: Run tests
        working-directory: LojadeCarro
        run: mvn test

      - name: Run tests with coverage
        working-directory: LojadeCarro
        run: mvn clean verify